### ISSUE TITLE
Unable to access extension configuration menu.

### ISSUE THREAD

**Issue by zelch** [wotmshuaisi/iqairGnomeExtension#1]
So, this is on Ubuntu 20.04, gnome-shell 3.36.7.

When trying to open the configuration settings, I get the 'Something's gone wrong' with the following details:

The settings of extension iqair@xjevvvv7_github had an error:
```
Error: No property group on GtkToggleButton
```

Stack trace:
```
_init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:63:40
buildPrefsWidget/<@/home/warp/.local/share/gnome-shell/extensions/iqair@xjevvvv7_github/prefs.js:53:20
buildPrefsWidget@/home/warp/.local/share/gnome-shell/extensions/iqair@xjevvvv7_github/prefs.js:52:26
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by wotmshuaisi** [comment]
Hello @zelch,

I recently updated this extension to make it compatible with Gnome 40. and according to Gtk API reference property `group` of GtkToggleButton is only available on Gtk 4.

I updated metadata to make sure gnome 3 users can avoid this issue. follow next steps:

1. Uninstall `iqair Gnome Extension` extension
2. Download `iqair Gnome Extension` extension (shell version 3.38, extension version: 6)
3. `mkdir -p ~/.local/share/gnome-shell/extensions/iqair@xjevvvv7_github`
3. Decompress zip file into folder `~/.local/share/gnome-shell/extensions/iqair@xjevvvv7_github`
4. If you are running Xorg Gnome, alt+f2, type `r` to restart gnome session
5. Logout and login in again if you are running Wayland Gnome

Once my new update got approval, you won't receive any Gnome 40 related updates as a gnome 3 user.
