### ISSUE TITLE
Problem with selecting country

### ISSUE THREAD

**Issue by sriwer** [wotmshuaisi/iqairGnomeExtension#2]
When I try to select my city (Sarajevo, Bosnia and Hercegovina) I get error

I select country "Bosnia Herzegovina"
I select state "Federation of B&H"  
_(there are two entities (states) Federation and Republika Srpska and only Federation can be selected)_

Then I get error 
IqairMenuButton-Settings
Remote server error:,400,{"status","fail","data":{message":"state_not_found"}}

https://www.iqair.com/bosnia-herzegovina/federation-of-b-h/sarajevo

If I can provide anything else let me know

s.

**Comment by wotmshuaisi** [comment]
Fixed with version 11. Currently waiting for review, will be available soon.
