### ISSUE TITLE
Cannot select country, state, and city

### ISSUE THREAD

**Issue by wuqso** [wotmshuaisi/iqairGnomeExtension#5]
It's a great extension and I once used it very well. After the system is upgraded into F36, there are errors, as I reported at extensions.gnome.org. Now I cannot select the country, state, and city in this extention. The tiny popup windows are blank and has no option to be selected.

**Comment by wotmshuaisi** [comment]
Can you provide further details about those errors you met and the Gnome version you are currently using?

**Comment by wuqso** [comment]
![Screenshot from 2022-05-26 20-49-45](https://user-images.githubusercontent.com/17075728/171007258-52cdc158-f3e1-4b95-95e8-4c6eb7bed4b8.png)
There is no options to be selected, as shown in the snapshot.
I'm using Gnome 42 and Fedora linux 36.

**Comment by wuqso** [comment]
![Screenshot from 2022-05-26 20-49-45](https://user-images.githubusercontent.com/17075728/171007918-68086a6f-0185-44a2-9139-9a854b302fb0.png)
There is no options to be selected, as shown in the snapshot.
I'm using Gnome 42 and Fedora linux 36.

**Comment by wotmshuaisi** [comment]
What do you see by executing the command `journalctl -f` while opening the settings window of the extension.

Kindly copy&past some logs here for helping me locate the problem.

**Comment by Strykar** [comment]
@wuqso Your free community API key has probably expired.
Check its validity in the JSON response as @wotmshuaisi suggested or create a new API key on the IQAir website.
Then restart Gnome or the extension and it will work.

@wotmshuaisi It might be nice to display to the last (fail) JSON response in the extension settings window to make things clearer to the user:
```
Apr 18 02:17:58 i-5 org.gnome.Shell.Extensions[198522]: [IqairMenuButton-Settings] Remote server error:, 402, {"status":"fail","data":{"message":"Payment Required"}}
Apr 18 02:17:58 i-5 org.gnome.Shell.Extensions[198522]: [IqairMenuButton-Settings] Built request, https://api.airvisual.com/v2/states?key=xxx&country=xxx
Apr 18 02:17:59 i-5 org.gnome.Shell.Extensions[198522]: [IqairMenuButton-Settings] Remote server error:, 402, {"status":"fail","data":{"message":"Payment Required"}}
Apr 18 02:17:59 i-5 org.gnome.Shell.Extensions[198522]: [IqairMenuButton-Settings] Built request, https://api.airvisual.com/v2/cities?key=xxx&country=xxx&state=xxx
Apr 18 02:18:00 i-5 org.gnome.Shell.Extensions[198522]: [IqairMenuButton-Settings] Remote server error:, 402, {"status":"fail","data":{"message":"Payment Required"}}
```

**Comment by wotmshuaisi** [comment]
> @wotmshuaisi It might be nice to display to the last (fail) JSON response in the extension settings window to make things clearer to the user:

A failed JSON response would display as a Gnome notification.
