### ISSUE TITLE
location error

### ISSUE THREAD

**Issue by wuqso** [wotmshuaisi/iqairGnomeExtension#6]
I can change the country from USA to another one, but the state still lists those of USA.

**Comment by wotmshuaisi** [comment]
Did you get any errors from journal logs?
Please help to check your journal logs by `journalctl -f` while you are repeating the same operations.

**Comment by wuqso** [comment]
Thanks for your reply. Here is the output of journalctl -f,

`Aug 31 19:05:11 ??? gnome-shell[3413]: Bug in client with pid 4121: Buffer size (64x64) is not aninteger multiple of the buffer_scale (3).
Aug 31 19:05:11 ??? gnome-shell[3413]: Bug in client with pid 4121: Buffer size (64x64) is not aninteger multiple of the buffer_scale (3).
Aug 31 19:05:11 ??? gnome-shell[3413]: Bug in client with pid 4121: Buffer size (64x64) is not aninteger multiple of the buffer_scale (3).
Aug 31 19:05:11 ??? thermald[1238]: Unable to find a sensor for \_UP_.NTC2
Aug 31 19:05:11 ??? thermald[1238]: Unable to find a sensor for \_UP_.CASE
Aug 31 19:05:11 ??? thermald[1238]: Unable to find a sensor for \_UP_.NTC2
Aug 31 19:05:11 ??? thermald[1238]: Unable to find a sensor for \_UP_.SOCB
Aug 31 19:05:11 ??? thermald[1238]: Unable to find a sensor for \_UP_.SOCB
Aug 31 19:05:11 ??? thermald[1238]: Unable to find a sensor for \_UP_.CASE
Aug 31 19:05:14 ??? gjs[18427]: [IqairMenuButton-Settings] Built request, https://api.airvisual.com/v2/states?key=xxxxxxxxxxxxxxxxxxxxxxxxx&country=Chile
Aug 31 19:05:14 ??? gjs[18427]: [IqairMenuButton-Settings] Remote server error:, 429, {"status":"fail","data":{"message":"Too Many Requests"}}
Aug 31 19:05:15 ??? thermald[1238]: Unable to find a sensor for \_UP_.NTC2
Aug 31 19:05:15 ??? thermald[1238]: Unable to find a sensor for \_UP_.CASE
Aug 31 19:05:15 ??? thermald[1238]: Unable to find a sensor for \_UP_.NTC2
Aug 31 19:05:15 ??? thermald[1238]: Unable to find a sensor for \_UP_.SOCB
Aug 31 19:05:15 ??? thermald[1238]: Unable to find a sensor for \_UP_.SOCB
Aug 31 19:05:15 ??? thermald[1238]: Unable to find a sensor for \_UP_.CASE
Aug 31 19:05:15 ??? thermald[1238]: Unable to find a sensor for \_UP_.NTC2
Aug 31 19:05:15 ??? thermald[1238]: Unable to find a sensor for \_UP_.SOCB
Aug 31 19:05:15 ??? thermald[1238]: Unable to find a sensor for \_UP_.SOCB
Aug 31 19:05:15 ??? thermald[1238]: Unable to find a sensor for \_UP_.CASE
Aug 31 19:05:19 ??? thermald[1238]: Unable to find a sensor for \_UP_.NTC2
Aug 31 19:05:19 ??? thermald[1238]: Unable to find a sensor for \_UP_.CASE
Aug 31 19:05:19 ??? thermald[1238]: Unable to find a sensor for \_UP_.NTC2
Aug 31 19:05:19 ??? thermald[1238]: Unable to find a sensor for \_UP_.SOCB
Aug 31 19:05:19 ??? thermald[1238]: Unable to find a sensor for \_UP_.SOCB
Aug 31 19:05:19 ??? thermald[1238]: Unable to find a sensor for \_UP_.CASE
Aug 31 19:05:23 ??? gjs[18427]: [IqairMenuButton-Settings] Country, State, City are not allowed to be empty.
Aug 31 19:05:23 ??? thermald[1238]: Unable to find a sensor for \_UP_.NTC2
Aug 31 19:05:23 ??? thermald[1238]: Unable to find a sensor for \_UP_.CASE
Aug 31 19:05:23 ??? thermald[1238]: Unable to find a sensor for \_UP_.NTC2
Aug 31 19:05:23 ??? thermald[1238]: Unable to find a sensor for \_UP_.SOCB
Aug 31 19:05:23 ??? thermald[1238]: Unable to find a sensor for \_UP_.SOCB
Aug 31 19:05:23 ??? thermald[1238]: Unable to find a sensor for \_UP_.CASE
Aug 31 19:05:25 ??? gnome-shell[3413]: Bug in client with pid 4121: Buffer size (64x64) is not aninteger multiple of the buffer_scale (3).
Aug 31 19:05:25 ??? gnome-shell[3413]: Bug in client with pid 4121: Buffer size (64x64) is not aninteger multiple of the buffer_scale (3).
Aug 31 19:05:26 ??? gnome-shell[3413]: Bug in client with pid 4121: Buffer size (64x64) is not aninteger multiple of the buffer_scale (3).
Aug 31 19:05:27 ??? thermald[1238]: Unable to find a sensor for \_UP_.NTC2
Aug 31 19:05:27 ??? thermald[1238]: Unable to find a sensor for \_UP_.CASE
Aug 31 19:05:27 ??? thermald[1238]: Unable to find a sensor for \_UP_.NTC2
Aug 31 19:05:27 ??? thermald[1238]: Unable to find a sensor for \_UP_.SOCB
Aug 31 19:05:27 ??? thermald[1238]: Unable to find a sensor for \_UP_.SOCB
Aug 31 19:05:27 ??? thermald[1238]: Unable to find a sensor for \_UP_.CASE
Aug 31 19:05:31 ??? thermald[1238]: Unable to find a sensor for \_UP_.NTC2
Aug 31 19:05:31 ??? thermald[1238]: Unable to find a sensor for \_UP_.CASE
Aug 31 19:05:31 ??? thermald[1238]: Unable to find a sensor for \_UP_.NTC2
Aug 31 19:05:31 ??? thermald[1238]: Unable to find a sensor for \_UP_.SOCB
Aug 31 19:05:31 ??? thermald[1238]: Unable to find a sensor for \_UP_.SOCB
Aug 31 19:05:31 ??? thermald[1238]: Unable to find a sensor for \_UP_.CASE
Aug 31 19:05:31 ??? gnome-shell[3413]: Bug in client with pid 4121: Buffer size (64x64) is not aninteger multiple of the buffer_scale (3).
Aug 31 19:05:31 ??? systemd[3200]: dbus-:1.2-org.gnome.Extensions@0.service: Consumed 1.492s CPU time.
Aug 31 19:05:31 ??? gnome-shell[3413]: ../gobject/gsignal.c:2731: instance '0x55864b627200' has no handler with id '85488'
Aug 31 19:05:33 ??? systemd[3200]: dbus-:1.2-org.gnome.Shell.Extensions@0.service: Consumed 3.516s CPU time.
`

**Comment by wotmshuaisi** [comment]
```
Aug 31 19:05:14 ??? gjs[18427]: [IqairMenuButton-Settings] Built request, https://api.airvisual.com/v2/states?key=xxxxxxxxxxxxxxxxxx&country=Chile
Aug 31 19:05:14 ??? gjs[18427]: [IqairMenuButton-Settings] Remote server error:, 429, {"status":"fail","data":{"message":"Too Many Requests"}}
```
I've tried your token, and your token seems to be fine.
I will make an update to slow down requests in the setting panel. For now, you should leave some gaps between each action in that window.

**Comment by wotmshuaisi** [comment]
The new release will switch from async to sync requests while adding a one-second delay before each request send out. Another thing to mention is extension will pop out a "Too many requests" notification when a request failed.
