### ISSUE TITLE
session.send_and_read error

### ISSUE THREAD

**Issue by DarylO71** [wotmshuaisi/iqairGnomeExtension#7]
This extension hasn't worked for me in several weeks, and when I try to open the settings, I get this error:

``The settings of extension iqair@wotmshuaisi_github had an error:
```
TypeError: session.send_and_read is not a function
```

Stack trace:
```
refreshDropDown@/home/xxxxxxx/.local/share/gnome-shell/extensions/iqair@wotmshuaisi_github/prefs.js:309:26
buildPrefsWidget@/home/xxxxxxx/.local/share/gnome-shell/extensions/iqair@wotmshuaisi_github/prefs.js:128:20
_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:32:44
ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:129:33
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

Does anyone know what could be the problem?

**Comment by wotmshuaisi** [comment]
If you are using Gnome 42 or lower, please try to reinstall the extension.

**Comment by DarylO71** [comment]
@wotmshuaisi I'm on GNOME 42.5, and I've already tried reinstalling the extension and that didn't help.  Is there a special procedure I should follow to uninstall it completely?

**Comment by DarylO71** [comment]
@wotmshuaisi I reinstalled it again but this time, I restarted GNOME Shell after uninstalling it, and now, it's working again after reinstalling.  Thanks for your help.
